<?php

/**
 * @var \AHT\Portfolio\Block\Catalog\Portfolio\PortfolioSlider $block
 */
$portfolioCollection = ($block->getPortfolioCollection());
?>
<?php if ($block->isEnabled()) : ?>
    <div class="block block-product-slider slider-list">
        <input type='hidden' id='portfolio_per_row' value='<?= $block->getData('portfolio_per_row') ?>' />
        <input type='hidden' id='slide_to_scroll' value='<?= $block->getData('slide_to_scroll') ?>' />
        <div class="block-title">
            <h1><?php echo $block->getTitle() ?></h1>
        </div>
        <div class="block-content">
            <?php if (count($portfolioCollection)) : ?>
                <div class="<?= (int)$block->getData('isSlider') === 1 ? 'product-slider' : 'product-container' ?>">
                    <?php foreach ($portfolioCollection as $portfolio) : ?>
                        <div class="product">
                            <div class="product-image">
                                <a href="<?= $block->getUrl('portfolio/index/view') . 'id/' . $portfolio['portfolio_id'] ?>">
                                    <?php if (count($portfolio['images']) > 0) { ?>
                                        <img src="<?= $portfolio['images'][0]['src'] ?>" alt="<?= $portfolio['images'][0]['thumbnail'] ?>" width='100%' />
                                    <?php } else { ?>
                                        <img src="<?= 'http://127.0.0.1/m235/pub/static/version1608915184/adminhtml/Magento/backend/en_US/Magento_Catalog/images/product/placeholder/thumbnail.jpg'  ?>" alt="image" width='100%' />
                                    <?php } ?>
                                </a>
                            </div>

                            <strong class="product-name">
                                <span><?= isset($portfolio['category']) ? $portfolio['category'] : '' ?></span>
                                <a href="<?= $block->getUrl('portfolio/index/view') . 'id/' . $portfolio['portfolio_id']  ?>">
                                    <h2><?= $portfolio['client'] ?></h2>
                                </a>
                                <p>
                                    <?= $portfolio['skill'] ?>
                                </p>
                            </strong>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    var portfolio_per_row = parseInt(document.getElementById('portfolio_per_row').value);
    var slide_to_scroll = parseInt(document.getElementById('slide_to_scroll').value);
    if (portfolio_per_row !== null) {
        require(['jquery', 'slick'], function($) {
            $(function() {
                $('.product-slider').slick({
                    dots: false,
                    infinite: false,
                    speed: 300,
                    slidesToShow: portfolio_per_row ? portfolio_per_row : 5,
                    slidesToScroll: slide_to_scroll > 0 ? slide_to_scroll : 4,
                    responsive: [{
                            breakpoint: 1024,
                            settings: {
                                slidesToShow: 4,
                                slidesToScroll: 4,
                                infinite: true
                            }
                        },
                        {
                            breakpoint: 770,
                            settings: {
                                slidesToShow: 3,
                                slidesToScroll: 2
                            }
                        },
                        {
                            breakpoint: 600,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                            }
                        },
                        {
                            breakpoint: 400,
                            settings: {
                                slidesToShow: 1,
                                slidesToScroll: 1
                            }
                        }
                    ]
                });
            });
        });
    }
</script>